[tableau]
token_name = "streamlit"
token_secret = "p1iA1RabTWGKcxiU3PrFPg==:z4YIfcbRxDorNKlJpjq8Kv0qV27H84R2"
server_url = "https://abc01.online.tableau.com/"
site_id = "streamlitexample"  # in your site's URL behind the server_url